name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened ]
env:
  IMAGE_NAME: scim-2-api-python
  IMAGE_TAG: main
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build-image
