name: Cosmos DB Integration Tests
on:
  push:
    branches: '*'
  pull_request:
    types: [ opened ]
env:
  CONFIG_PATH: "./config/integration-tests-cosmos-store.yaml"
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Install dependencies
        run: poetry install
      - name: Generate Cosmos DB container name
        run: export STORE_COSMOS_DB_NAME=scim_int_tsts_$(date +%s)
      - name: Integration tests (In-memory store)
        run: |
          STORE_COSMOS_ACCOUNT_URI="${{ secrets.COSMOS_ACCOUNT_URI }}" \
          STORE_COSMOS_ACCOUNT_KEY="${{ secrets.COSMOS_ACCOUNT_KEY }}" \
          poetry run run pytest tests/integration -p no:warnings --verbose --asyncio-mode=strict
      - name: Clean up
        run: |
          STORE_COSMOS_ACCOUNT_URI="${{ secrets.COSMOS_ACCOUNT_URI }}" \
          STORE_COSMOS_ACCOUNT_KEY="${{ secrets.COSMOS_ACCOUNT_KEY }}" \
          poetry run tests/integration/scripts/cleanup.py
